name: absensi_mobile
description: "Aplikasi Presensi Mobile Karyawan dengan Biometrik Wajah dan Geofencing GPS"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  camera: ^0.10.5+9
  geolocator: ^10.1.0
  http: ^1.2.0
  shared_preferences: ^2.2.2
  intl: ^0.19.0
  cupertino_icons: ^1.0.6
  http_parser: ^4.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "lib/asset/icon/app_logo.png"
  min_sdk_android: 21
  remove_alpha_ios: true

flutter:
  uses-material-design: true
  assets:
    - lib/asset/baground/
    - lib/asset/icon/
    - assets/baground/
    - assets/icon/


